"""empty message

Revision ID: 0b6a6277aa63
Revises: 7c647be9507a
Create Date: 2023-07-07 15:30:12.469837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b6a6277aa63'
down_revision = '7c647be9507a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversion_uuid', sa.String(length=32), nullable=False))
        batch_op.drop_constraint('files_ibfk_3', type_='foreignkey')
        batch_op.drop_column('converted_from_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('converted_from_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('files_ibfk_3', 'files', ['converted_from_id'], ['id'])
        batch_op.drop_column('conversion_uuid')

    # ### end Alembic commands ###
