"""empty message

Revision ID: 7c647be9507a
Revises: fdac55ca1503
Create Date: 2023-07-07 04:00:19.517594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c647be9507a'
down_revision = 'fdac55ca1503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('converted_from_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'files', ['converted_from_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('converted_from_id')

    # ### end Alembic commands ###
