"""empty message

Revision ID: bf0dbd679a45
Revises: fd987a34b598
Create Date: 2023-07-11 15:55:41.148304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0dbd679a45'
down_revision = 'fd987a34b598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_access', schema=None) as batch_op:
        batch_op.drop_constraint('project_access_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_access', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_access_ibfk_2', 'auth_user', ['project_id'], ['id'])

    # ### end Alembic commands ###
