  SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://root:anirudh@localhost:3306/starter_kit_test'
  JWT_SECRET_KEY: 'ee4c120c-e5ee-40cf-85ef-cc1505d936aa'
  JWT_ACCESS_TOKEN_EXPIRES: !timedelta '1440 minutes'
  JWT_REFRESH_TOKEN_EXPIRES: !timedelta '1440 minutes'
  SECRET_KEY: 'ee4c120c-e5ee-40cf-85ef-cc1505d936aa'
  PROPAGATE_EXCEPTIONS: true
  SERVER_PATH: ""